spring:
  kafka:
    bootstrap-servers: localhost:9092
    properties:
      ssl:
        truststore:
          type: PEM
          location: ${user.dir}/src/main/resources/ca.pem
        keystore:
          type: PKCS12
          location: ${user.dir}/src/main/resources/client.keystore.p12
          password: changeit
  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: postgres
    password: postgres

app:
  inventory:
    base-url: http://localhost:8081
